# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-lambda-pokemon-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:
    region: ${self:provider.region}
    APIGATEWAY_NAME_POKEMON: pokemonAPI
    APIGATEWAY_CONSULTA: consulta
    DYNAMODB_TABLE_NAME: listapokemon


functions:
  GetPokemon:
    handler: getPokemon.handler
    memorySize: 128
    events: 
      - http:
          path: /${self:provider.environment.APIGATEWAY_NAME_POKEMON}/{resource}/{namePokemon}
          method: get
          cors: true
          private: true
      - http:
          path: /${self:provider.environment.APIGATEWAY_NAME_POKEMON}/{resource}
          method: get
          cors: true
          private: true
      
   
  AddPokemon:
    handler: addPokemon.handler
    memorySize: 128
    events:
      - http:
          path: /${self:provider.environment.APIGATEWAY_CONSULTA}/add
          method: post
          cors: true

# you can add CloudFormation resource templates here
resources:
  Resources:

    NewResource:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: idPokemon
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: idPokemon
            KeyType: HASH  

          

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
